version: '3'

services:
  database:
    container_name: database
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./src/server/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=password
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - mycelium

  web:
    container_name: website
    build:
      context: ./src/web
      dockerfile: ./Dockerfile
    ports:
      - "9000"
    networks:
      - "mycelium"

  api:
    build:
      context: ./src/server
      dockerfile: ./Dockerfile
    ports:
      - "3000"
    volumes:
      - "./src/server/data:/app/data"
      - "./src/server/endpoints:/app/endpoints"
      - "./src/server/scripts:/app/scripts"
      - "./src/server/utils:/app/utils"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=plants
    depends_on:
      database:
        condition: service_healthy 
    networks:
      - mycelium

  nginx:
    container_name: nginxweb
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - web
    networks:
      - mycelium

volumes:
  data:

networks:
  mycelium:
    driver: bridge