version: '3'

services:
  database:
    container_name: database
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./src/server/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=password
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - mycelium

  flaskserver:
    container_name: flaskserver
    build:
      context: ./src/server
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=plants
    depends_on:
      database:
        condition: service_healthy 
    networks:
      - mycelium

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     # - react-app
  #     - flaskserver

volumes:
  data:

networks:
  mycelium: